function [rawResults, summaryResults] = runPfModuleAblation(mode, nParticles, pfSeeds, mapSeeds)
%RUNPFMODULEABLATION Full-trajectory module/rule ablation runner.
%
% Examples:
%   runPfModuleAblation("smoke")    % syntax/data-path validation
%   runPfModuleAblation("screen")   % 500 particles, 3 PF seeds
%   runPfModuleAblation("confirm")  % 1500 particles, 5 PF seeds
%   runPfModuleAblation("combo_particle_sweep") % requested minimal-combo sweep
%   runPfModuleAblation("motion_threshold_sweep") % yaw/pitch rejection tuning
%   runPfModuleAblation("gt_zero_screen") % zero map error, GT Bezier, no init alignment
%   runPfModuleAblation("gt_zero_confirm") % 1500-particle confirmation for gt_zero_screen

    if nargin < 1 || isempty(mode)
        mode = "screen";
    end
    mode = lower(string(mode));

    addpath estimator\ map\ math\ rosservice\ utils\

    baseCfg = loadConfig();
    baseCfg.yamlLogProgress = false;
    baseCfg.pfLogProgress = false;
    baseCfg.pfVisualizeMapMatching = false;
    baseCfg = applyModeBaseConfig(baseCfg, mode);

    if nargin < 2 || isempty(nParticles)
        nParticles = defaultParticleCount(mode);
    end
    nParticleList = nParticles(:).';
    if nargin < 3 || isempty(pfSeeds)
        pfSeeds = defaultPfSeeds(mode);
    end
    if nargin < 4 || isempty(mapSeeds)
        mapSeeds = defaultMapSeeds(mode, baseCfg);
    end

    variants = makeVariants(mode);
    outDir = fullfile(fileparts(mfilename('fullpath')), 'ablation_logs');
    if ~exist(outDir, 'dir')
        mkdir(outDir);
    end

    fprintf('PF module ablation mode=%s, particleCounts=[%s], pfSeeds=[%s], mapSeeds=[%s], variants=%d\n', ...
        mode, num2str(nParticleList), num2str(pfSeeds), num2str(mapSeeds), numel(variants));

    rows = repmat(emptyResultRow(), 0, 1);
    runStart = tic;

    for iMap = 1:numel(mapSeeds)
        mapSeed = mapSeeds(iMap);
        cfgMap = applyMapInitSeed(baseCfg, mapSeed);
        data = loadExperimentData(cfgMap);

        for iVariant = 1:numel(variants)
            variant = variants(iVariant);
            cfgVariant = applyParams(cfgMap, variant.params);
            cfgVariant.ablationTag = variant.name;
            cfgVariant.ablationNotes = variant.description;

            fprintf('\n[%d/%d map %d/%d] %s | %s\n', ...
                iVariant, numel(variants), iMap, numel(mapSeeds), ...
                variant.name, variant.description);

            stats = countBezierDatasetStats(cfgVariant, data.queryBezier);
            [x0, x0Align, alignInfo, alignElapsedSec] = computeInitialState(cfgVariant, data);
            p0 = initialCovariance(cfgVariant);

            for iParticle = 1:numel(nParticleList)
                for iSeed = 1:numel(pfSeeds)
                    cfg = cfgVariant;
                    cfg.pfNumParticles = nParticleList(iParticle);
                    cfg.pfRandomSeed = pfSeeds(iSeed);
                    fprintf('  seed=%d, N=%d ... ', cfg.pfRandomSeed, cfg.pfNumParticles);

                    elapsedTimer = tic;
                    [xhat, nEff, pfDiag] = sir(cfg, data.mapDB, x0, p0, ...
                        data.dSE2, data.queryBezier, [], data.len, cfg.pfNumParticles);
                    elapsedSec = toc(elapsedTimer);

                    xhatGt = recenterStatesByPose(xhat, data.xTrue0InMap);
                    metrics = evaluateTrajectories(data.gtXY, data.vioXY, xhatGt(1:2, :));
                    diagSummary = summarizePfDiag(pfDiag, nEff, cfg.pfNumParticles);

                    row = emptyResultRow();
                    row.mode = mode;
                    row.variantName = variant.name;
                    row.stage = variant.stage;
                    row.description = variant.description;
                    row.moduleSet = variant.moduleSet;
                    row.nParticles = cfg.pfNumParticles;
                    row.pfSeed = cfg.pfRandomSeed;
                    row.mapSeed = mapSeed;
                    row.nSamples = metrics.n;
                    row.vioRmse = metrics.vio.rmse;
                    row.pfRmse = metrics.pf.rmse;
                    row.improvement = metrics.rmseImprovement;
                    row.improvementPct = metrics.rmseImprovementPct;
                    row.beatsVio = metrics.pf.rmse < metrics.vio.rmse;
                    row.vioMeanError = metrics.vio.mean;
                    row.pfMeanError = metrics.pf.mean;
                    row.vioFinalError = metrics.vio.final;
                    row.pfFinalError = metrics.pf.final;
                    row.pfAxisRmseX = metrics.pf.axisRmse(1);
                    row.pfAxisRmseY = metrics.pf.axisRmse(2);
                    row.alignElapsedSec = alignElapsedSec;
                    row.alignX = x0Align(1);
                    row.alignY = x0Align(2);
                    row.alignYawDeg = rad2deg(x0Align(3));
                    row.alignLogLikelihood = getStructScalar(alignInfo, 'logLikelihood', NaN);
                    row.alignSelectedFrames = selectedFrameCount(alignInfo);
                    row.usableFrames = stats.usableFrames;
                    row.usableCurves = stats.usableCurves;
                    row.rejectYawing = stats.rejectYawing;
                    row.rejectPitching = stats.rejectPitching;
                    row.rejectShortChord = stats.rejectShortChord;
                    row.rejectNearBody = stats.rejectNearBody;
                    row.rejectIsolatedStart = stats.rejectIsolatedStart;
                    row.usedUpdateFrames = diagSummary.usedUpdateFrames;
                    row.resampleCount = diagSummary.resampleCount;
                    row.meanNeffRatio = diagSummary.meanNeffRatio;
                    row.stdNeffRatio = diagSummary.stdNeffRatio;
                    row.meanAssociatedParticleRatio = diagSummary.meanAssociatedParticleRatio;
                    row.meanRoadGatePassRatio = diagSummary.meanRoadGatePassRatio;
                    row.meanMatchedCurveCount = diagSummary.meanMatchedCurveCount;
                    row.meanResidual = diagSummary.meanResidual;
                    row.elapsedSec = elapsedSec;

                    rows(end + 1) = row; %#ok<AGROW>
                    fprintf('PF RMSE=%.3f, VIO RMSE=%.3f, improvement=%.2f%%, N_eff=%.2f, %.1fs\n', ...
                        row.pfRmse, row.vioRmse, row.improvementPct, row.meanNeffRatio, elapsedSec);
                end
            end
        end
    end

    rawResults = struct2table(rows);
    summaryResults = summarizeResults(rawResults);

    timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    rawPath = fullfile(outDir, sprintf('pf_module_ablation_%s_raw_%s.csv', mode, timestamp));
    summaryPath = fullfile(outDir, sprintf('pf_module_ablation_%s_summary_%s.csv', mode, timestamp));
    writetable(rawResults, rawPath);
    writetable(summaryResults, summaryPath);

    latestRawPath = fullfile(outDir, sprintf('pf_module_ablation_%s_raw_latest.csv', mode));
    latestSummaryPath = fullfile(outDir, sprintf('pf_module_ablation_%s_summary_latest.csv', mode));
    writetable(rawResults, latestRawPath);
    writetable(summaryResults, latestSummaryPath);

    fprintf('\nSaved raw results: %s\n', rawPath);
    fprintf('Saved summary    : %s\n', summaryPath);
    fprintf('Total elapsed    : %.1f sec\n', toc(runStart));
    disp(summaryResults);
end

function cfg = applyModeBaseConfig(cfg, mode)
    if ~startsWith(mode, "gt_zero")
        return;
    end

    % Requested GT-query / zero-map-error condition. Initial alignment is
    % intentionally disabled because the map and query frames start aligned.
    cfg.yamlDir = 'D:\Comple Urban\Urban26\stereo_left_bezier_gt';
    cfg.mapInitErrorSeed = NaN;
    cfg.mapInitXError = 0.0;
    cfg.mapInitYError = 0.0;
    cfg.mapInitYawError = 0.0;
    cfg.initUse = false;
    cfg.initUseTrajectoryAlignment = false;
    cfg.initUseLongitudinalCorrection = false;
    cfg.pfInitXStd = 0.0;
    cfg.pfInitYStd = 0.0;
    cfg.pfInitYawStdDeg = 0.0;

    % Use a canonical full-module baseline for this ablation mode so that
    % one-at-a-time/backward variants still mean "remove from full".
    cfg.pfProcessNoiseFrame = 'body';
    cfg.pfUseMeasurementUpdate = true;
    cfg.pfLikelihoodTemperature = 6.0;
    cfg.pfLikelihoodMaxLogSpan = 22.0;
    cfg.pfWeightUniformMix = 0.02;
    cfg.pfMinAssociatedParticleRatio = 0.02;
    cfg.pfRoughenAfterResample = true;

    cfg.assocUseYawingRejection = true;
    cfg.assocUsePitchingRejection = true;
    cfg.assocUseMinCurveChordRule = true;
    cfg.assocUseMinBodyDistanceRule = true;
    cfg.assocUseStartConnectionRule = true;
    cfg.assocRequireStartConnection = false;
    cfg.assocAllowSingleCurveWithoutConnection = true;
    cfg.assocUseBodyRoadGate = true;
    cfg.assocUseCurveMapCorrespondenceRule = true;
    cfg.assocUseCameraFovGate = true;

    cfg.likelihoodUseRobust = true;
    cfg.likelihoodMaxEffectiveSamples = 12;
    cfg.likelihoodInlierReward = 0.75;
end

function nParticles = defaultParticleCount(mode)
    if mode == "combo_particle_sweep"
        nParticles = [10, 100, 500, 1500];
    elseif mode == "motion_threshold_sweep"
        nParticles = 500;
    elseif mode == "gt_zero_confirm"
        nParticles = 1500;
    elseif mode == "confirm"
        nParticles = 1500;
    elseif mode == "smoke"
        nParticles = 100;
    else
        nParticles = 500;
    end
end

function seeds = defaultPfSeeds(mode)
    if mode == "confirm" || mode == "combo_particle_sweep" || ...
            mode == "motion_threshold_sweep" || mode == "gt_zero_confirm"
        seeds = [7, 11, 13, 17, 19];
    elseif mode == "smoke"
        seeds = 7;
    else
        seeds = [7, 11, 13];
    end
end

function mapSeeds = defaultMapSeeds(mode, baseCfg)
    if startsWith(mode, "gt_zero")
        mapSeeds = NaN;
    else
        mapSeeds = getScalar(baseCfg, 'mapInitErrorSeed', 7);
    end
end

function variants = makeVariants(mode)
    variants = allVariants();
    if mode == "smoke"
        keep = ["pf_minimal", "pf_full", "no_measurement_update"];
        variants = variants(ismember([variants.name], keep));
    elseif mode == "confirm"
        keep = ["pf_full", "map_frame_process_noise", "back_no_pf_stabilization", ...
            "ix_no_fov_wide_assoc", "no_inlier_reward", "no_body_road_gate", ...
            "ix_no_geometry_query_rules", "back_no_query_rules", "back_no_map_gates", ...
            "fwd_07_query_rules", "fwd_09_trajectory_init", ...
            "gaussian_likelihood", "back_no_likelihood_shaping"];
        variants = variants(ismember([variants.name], keep));
    elseif mode == "combo_particle_sweep"
        keep = "combo_map_noise_no_query_no_body_road";
        variants = variants(ismember([variants.name], keep));
    elseif mode == "motion_threshold_sweep"
        variants = motionThresholdVariants();
    elseif mode == "gt_zero_screen"
        keep = gtZeroScreenKeepList();
        variants = variants(ismember([variants.name], keep));
    elseif mode == "gt_zero_confirm"
        keep = ["pf_minimal", "pf_full", "no_measurement_update", ...
            "fwd_02_measurement_basic", "fwd_07_query_rules", ...
            "back_no_pf_stabilization", "ix_no_robust_no_temp_clip", ...
            "no_likelihood_temperature", "no_weight_uniform_mix", ...
            "no_adaptive_process_scale", "no_effective_sample_cap", ...
            "map_frame_process_noise", "combo_map_noise_no_query_no_body_road", ...
            "back_no_query_rules", "back_no_map_gates", ...
            "gaussian_likelihood", "back_no_likelihood_shaping", ...
            "strict_start_connection"];
        variants = variants(ismember([variants.name], keep));
    end
end

function keep = gtZeroScreenKeepList()
    keep = ["pf_minimal", "pf_full", ...
        "no_measurement_update", ...
        "no_yawing_reject", "no_pitching_reject", "no_short_chord_rule", ...
        "no_near_body_rule", "strict_start_connection", ...
        "no_body_road_gate", "no_curve_correspondence_rule", "no_camera_fov_gate", ...
        "gaussian_likelihood", "no_inlier_reward", "no_effective_sample_cap", ...
        "no_likelihood_temperature", "no_likelihood_log_clip", ...
        "no_weight_uniform_mix", "no_association_ratio_gate", ...
        "no_roughening", "map_frame_process_noise", "no_adaptive_process_scale", ...
        "fwd_00_minimal", "fwd_01_pf_stabilization", ...
        "fwd_02_measurement_basic", "fwd_03_curve_correspondence", ...
        "fwd_04_body_road_gate", "fwd_05_robust_likelihood", ...
        "fwd_06_likelihood_stabilization", "fwd_07_query_rules", ...
        "fwd_08_camera_fov_gate", ...
        "ix_no_road_no_correspondence", "ix_no_robust_no_temp_clip", ...
        "ix_no_motion_rejects", "ix_no_geometry_query_rules", ...
        "ix_fov_wide_assoc", "ix_no_fov_wide_assoc", "ix_strict_start_low_info", ...
        "back_no_query_rules", "back_no_map_gates", ...
        "back_no_pf_stabilization", "back_no_likelihood_shaping"];
end

function variants = allVariants()
    variants = struct('name', {}, 'stage', {}, 'description', {}, 'moduleSet', {}, 'params', {});

    variants(end + 1) = variant("pf_minimal", "baseline", ...
        "Propagation-only PF with zero initial/process noise", ...
        "PF minimal", pfMinimalParams());
    variants(end + 1) = variant("pf_full", "baseline", ...
        "Current default full PF pipeline", ...
        "PF full", struct());

    variants(end + 1) = variant("no_measurement_update", "one_at_a_time", ...
        "Full pipeline without Bezier-map measurement updates", ...
        "Full - measurement update", struct('pfUseMeasurementUpdate', false));
    variants(end + 1) = variant("no_init_alignment", "one_at_a_time", ...
        "Full pipeline but PF starts at [0 0 0]", ...
        "Full - initial alignment", struct('initUse', false, ...
        'pfInitXStd', 0.0, 'pfInitYStd', 0.0, 'pfInitYawStdDeg', 0.0));
    variants(end + 1) = variant("single_frame_init", "one_at_a_time", ...
        "Use first usable Bezier frame instead of early trajectory alignment", ...
        "Full - trajectory init", struct('initUseTrajectoryAlignment', false));
    variants(end + 1) = variant("no_longitudinal_correction", "one_at_a_time", ...
        "Apply alignment yaw/lateral correction but force initial x to zero", ...
        "Full - longitudinal correction", struct('initUseLongitudinalCorrection', false));
    variants(end + 1) = variant("no_init_prior_score", "one_at_a_time", ...
        "Disable weak trajectory-initialization prior score", ...
        "Full - init prior", struct('initUsePriorScore', false));
    variants(end + 1) = variant("coarse_init_only", "one_at_a_time", ...
        "Skip fine grid refinement after coarse initialization search", ...
        "Full - init fine search", struct('initUseFineSearch', false));

    variants(end + 1) = variant("no_yawing_reject", "one_at_a_time", ...
        "Allow query curves captured during yawing", ...
        "Full - yawing rejection", struct('assocUseYawingRejection', false));
    variants(end + 1) = variant("no_pitching_reject", "one_at_a_time", ...
        "Allow query curves captured during pitching", ...
        "Full - pitching rejection", struct('assocUsePitchingRejection', false));
    variants(end + 1) = variant("no_short_chord_rule", "one_at_a_time", ...
        "Disable start/end chord-length query filter", ...
        "Full - short chord rule", struct('assocUseMinCurveChordRule', false));
    variants(end + 1) = variant("no_near_body_rule", "one_at_a_time", ...
        "Disable body-proximity query filter", ...
        "Full - near-body rule", struct('assocUseMinBodyDistanceRule', false));
    variants(end + 1) = variant("strict_start_connection", "one_at_a_time", ...
        "Enable isolated curve start rejection", ...
        "Full + start connection rule", struct('assocRequireStartConnection', true, ...
        'assocAllowSingleCurveWithoutConnection', false, 'assocConnectionTol', 3.0));

    variants(end + 1) = variant("no_body_road_gate", "one_at_a_time", ...
        "Disable body-to-road-width gate before curve matching", ...
        "Full - body road gate", struct('assocUseBodyRoadGate', false));
    variants(end + 1) = variant("no_curve_correspondence_rule", "one_at_a_time", ...
        "Score all usable curves without requiring map correspondences", ...
        "Full - curve-map correspondence rule", struct('assocUseCurveMapCorrespondenceRule', false));
    variants(end + 1) = variant("no_camera_fov_gate", "one_at_a_time", ...
        "Disable camera-FOV-limited map association", ...
        "Full - camera FOV gate", struct('assocUseCameraFovGate', false));

    variants(end + 1) = variant("gaussian_likelihood", "one_at_a_time", ...
        "Use non-robust Gaussian residual cost", ...
        "Full - robust likelihood", struct('likelihoodUseRobust', false));
    variants(end + 1) = variant("no_inlier_reward", "one_at_a_time", ...
        "Remove reward for high inlier fraction", ...
        "Full - inlier reward", struct('likelihoodInlierReward', 0.0));
    variants(end + 1) = variant("no_effective_sample_cap", "one_at_a_time", ...
        "Use every sampled point as likelihood information", ...
        "Full - effective sample cap", struct('likelihoodMaxEffectiveSamples', inf));
    variants(end + 1) = variant("no_likelihood_temperature", "one_at_a_time", ...
        "Remove likelihood temperature scaling", ...
        "Full - likelihood temperature", struct('pfLikelihoodTemperature', 1.0));
    variants(end + 1) = variant("no_likelihood_log_clip", "one_at_a_time", ...
        "Remove per-frame log-likelihood span clipping", ...
        "Full - likelihood log clipping", struct('pfLikelihoodMaxLogSpan', inf));
    variants(end + 1) = variant("no_weight_uniform_mix", "one_at_a_time", ...
        "Remove uniform mixture after weight update", ...
        "Full - uniform weight mix", struct('pfWeightUniformMix', 0.0));
    variants(end + 1) = variant("no_association_ratio_gate", "one_at_a_time", ...
        "Always use a measurement frame if it has finite likelihoods", ...
        "Full - associated-particle ratio gate", struct('pfMinAssociatedParticleRatio', 0.0));
    variants(end + 1) = variant("no_roughening", "one_at_a_time", ...
        "Disable post-resampling particle roughening", ...
        "Full - roughening", struct('pfRoughenAfterResample', false));
    variants(end + 1) = variant("map_frame_process_noise", "one_at_a_time", ...
        "Inject process noise in map frame instead of body frame", ...
        "Full - body-frame process noise", struct('pfProcessNoiseFrame', 'map'));
    variants(end + 1) = variant("combo_map_noise_no_query_no_body_road", "particle_sweep", ...
        "Map-frame process noise with query-only filters and body-road gate disabled", ...
        "map noise + no query rules + no body road gate", ...
        struct('pfProcessNoiseFrame', 'map', ...
        'assocUseYawingRejection', false, ...
        'assocUsePitchingRejection', false, ...
        'assocUseMinCurveChordRule', false, ...
        'assocUseMinBodyDistanceRule', false, ...
        'assocUseBodyRoadGate', false));
    variants(end + 1) = variant("no_adaptive_process_scale", "one_at_a_time", ...
        "Keep process noise floors but remove distance/yaw scaling", ...
        "Full - adaptive process scale", struct('pfProcessTransScale', 0.0, 'pfProcessYawScale', 0.0));

    variants = [variants, forwardSelectionVariants(), interactionVariants(), ...
        backwardVariants(), motionThresholdVariants()]; %#ok<AGROW>
end

function variants = forwardSelectionVariants()
    variants = struct('name', {}, 'stage', {}, 'description', {}, 'moduleSet', {}, 'params', {});
    base = pfMinimalParams();

    variants(end + 1) = variant("fwd_00_minimal", "forward", ...
        "Forward-selection start: odometry propagation only", ...
        "minimal", base);

    params = mergeStructs(base, pfStabilizationParams());
    variants(end + 1) = variant("fwd_01_pf_stabilization", "forward", ...
        "Add stabilized PF process model while still propagation-only", ...
        "minimal + PF stabilization", params);

    params = mergeStructs(base, pfStabilizationParams(), measurementMinimalParams());
    variants(end + 1) = variant("fwd_02_measurement_basic", "forward", ...
        "Add measurement update with query/map gates disabled", ...
        "prev + measurement", params);

    params = mergeStructs(params, struct('assocUseCurveMapCorrespondenceRule', true));
    variants(end + 1) = variant("fwd_03_curve_correspondence", "forward", ...
        "Add curve-map correspondence requirement", ...
        "prev + curve correspondence", params);

    params = mergeStructs(params, struct('assocUseBodyRoadGate', true));
    variants(end + 1) = variant("fwd_04_body_road_gate", "forward", ...
        "Add body-road-width gate", ...
        "prev + body road gate", params);

    params = mergeStructs(params, robustLikelihoodParams());
    variants(end + 1) = variant("fwd_05_robust_likelihood", "forward", ...
        "Add robust residual model and penalties", ...
        "prev + robust likelihood", params);

    params = mergeStructs(params, likelihoodStabilizationParams());
    variants(end + 1) = variant("fwd_06_likelihood_stabilization", "forward", ...
        "Add likelihood temperature, clipping, and uniform mix", ...
        "prev + likelihood stabilization", params);

    params = mergeStructs(params, queryRuleParams());
    variants(end + 1) = variant("fwd_07_query_rules", "forward", ...
        "Add query-only yaw/pitch/chord/body filters", ...
        "prev + query rules", params);

    params = mergeStructs(params, struct('assocUseCameraFovGate', true));
    variants(end + 1) = variant("fwd_08_camera_fov_gate", "forward", ...
        "Add camera FOV gate", ...
        "prev + FOV gate", params);

    params = mergeStructs(params, initAlignmentParams());
    variants(end + 1) = variant("fwd_09_trajectory_init", "forward", ...
        "Add trajectory initial alignment as PF initial state", ...
        "prev + trajectory init", params);
end

function variants = interactionVariants()
    variants = struct('name', {}, 'stage', {}, 'description', {}, 'moduleSet', {}, 'params', {});

    variants(end + 1) = variant("ix_no_road_no_correspondence", "interaction", ...
        "Disable both map-side road gate and correspondence gate", ...
        "Full - road gate - correspondence", struct('assocUseBodyRoadGate', false, ...
        'assocUseCurveMapCorrespondenceRule', false));
    variants(end + 1) = variant("ix_no_robust_no_temp_clip", "interaction", ...
        "Disable robust likelihood and PF likelihood stabilization together", ...
        "Full - robust - temp/clip/mix", struct('likelihoodUseRobust', false, ...
        'pfLikelihoodTemperature', 1.0, 'pfLikelihoodMaxLogSpan', inf, 'pfWeightUniformMix', 0.0));
    variants(end + 1) = variant("ix_no_motion_rejects", "interaction", ...
        "Disable yawing and pitching query rejections together", ...
        "Full - yaw/pitch rejects", struct('assocUseYawingRejection', false, ...
        'assocUsePitchingRejection', false));
    variants(end + 1) = variant("ix_no_geometry_query_rules", "interaction", ...
        "Disable chord and body-distance query filters together", ...
        "Full - chord/body query rules", struct('assocUseMinCurveChordRule', false, ...
        'assocUseMinBodyDistanceRule', false));
    variants(end + 1) = variant("ix_no_init_no_longitudinal", "interaction", ...
        "Disable trajectory init and longitudinal correction path", ...
        "Full - init bundle", struct('initUse', false, ...
        'initUseLongitudinalCorrection', false, 'pfInitXStd', 0.0, ...
        'pfInitYStd', 0.0, 'pfInitYawStdDeg', 0.0));
    variants(end + 1) = variant("ix_fov_wide_assoc", "interaction", ...
        "Keep FOV gate but loosen curve-map residual gate", ...
        "FOV x wide association", struct('assocUseCameraFovGate', true, ...
        'assocMaxCurveMapDist', 7.0, 'likelihoodSigma', 2.0));
    variants(end + 1) = variant("ix_no_fov_wide_assoc", "interaction", ...
        "Disable FOV gate while loosening residual gate", ...
        "No FOV x wide association", struct('assocUseCameraFovGate', false, ...
        'assocMaxCurveMapDist', 7.0, 'likelihoodSigma', 2.0));
    variants(end + 1) = variant("ix_strict_start_low_info", "interaction", ...
        "Enable strict start connection while lowering measurement information", ...
        "strict start x low information", struct('assocRequireStartConnection', true, ...
        'assocAllowSingleCurveWithoutConnection', false, 'pfLikelihoodTemperature', 7.0, ...
        'pfLikelihoodMaxLogSpan', 18.0, 'likelihoodMaxEffectiveSamples', 10, ...
        'likelihoodInlierReward', 0.5));
end

function variants = backwardVariants()
    variants = struct('name', {}, 'stage', {}, 'description', {}, 'moduleSet', {}, 'params', {});
    variants(end + 1) = variant("back_no_query_rules", "backward", ...
        "Backward elimination: remove all current query-only filters", ...
        "Full - all query rules", struct('assocUseYawingRejection', false, ...
        'assocUsePitchingRejection', false, 'assocUseMinCurveChordRule', false, ...
        'assocUseMinBodyDistanceRule', false));
    variants(end + 1) = variant("back_no_map_gates", "backward", ...
        "Backward elimination: remove road, FOV, and correspondence gates", ...
        "Full - all map gates", struct('assocUseBodyRoadGate', false, ...
        'assocUseCameraFovGate', false, 'assocUseCurveMapCorrespondenceRule', false));
    variants(end + 1) = variant("back_no_pf_stabilization", "backward", ...
        "Backward elimination: remove temperature, clipping, mix, roughening, and body-frame process noise", ...
        "Full - PF stabilization", struct('pfLikelihoodTemperature', 1.0, ...
        'pfLikelihoodMaxLogSpan', inf, 'pfWeightUniformMix', 0.0, ...
        'pfMinAssociatedParticleRatio', 0.0, 'pfProcessNoiseFrame', 'map', ...
        'pfRoughenAfterResample', false));
    variants(end + 1) = variant("back_no_likelihood_shaping", "backward", ...
        "Backward elimination: remove robust residual, inlier reward, and sample cap", ...
        "Full - likelihood shaping", struct('likelihoodUseRobust', false, ...
        'likelihoodInlierReward', 0.0, 'likelihoodMaxEffectiveSamples', inf));
end

function variants = motionThresholdVariants()
    variants = struct('name', {}, 'stage', {}, 'description', {}, 'moduleSet', {}, 'params', {});

    variants(end + 1) = motionVariant("motion_off", false, false, 25.0, 10.0, ...
        "Motion rejection disabled baseline");
    variants(end + 1) = motionVariant("motion_y25_p10", true, true, 25.0, 10.0, ...
        "Enable current yaw/pitch thresholds");
    variants(end + 1) = motionVariant("motion_y20_p8", true, true, 20.0, 8.0, ...
        "Moderately stricter yaw/pitch thresholds");
    variants(end + 1) = motionVariant("motion_y15_p6", true, true, 15.0, 6.0, ...
        "Stricter yaw/pitch thresholds");
    variants(end + 1) = motionVariant("motion_y10_p5", true, true, 10.0, 5.0, ...
        "Strict yaw/pitch thresholds");
    variants(end + 1) = motionVariant("motion_y7p5_p3", true, true, 7.5, 3.0, ...
        "Very strict yaw/pitch thresholds");
    variants(end + 1) = motionVariant("motion_y5_p2", true, true, 5.0, 2.0, ...
        "Aggressive yaw/pitch thresholds");
    variants(end + 1) = motionVariant("motion_y10_only", true, false, 10.0, 10.0, ...
        "Strict yaw-only threshold");
    variants(end + 1) = motionVariant("motion_p5_only", false, true, 25.0, 5.0, ...
        "Strict pitch-only threshold");
end

function v = motionVariant(name, useYaw, usePitch, yawThresh, pitchThresh, description)
    params = struct( ...
        'pfProcessNoiseFrame', 'map', ...
        'assocUseYawingRejection', useYaw, ...
        'assocUsePitchingRejection', usePitch, ...
        'assocMaxYawRateDegPerSec', yawThresh, ...
        'assocMaxPitchRateDegPerSec', pitchThresh, ...
        'assocUseMinCurveChordRule', false, ...
        'assocUseMinBodyDistanceRule', false, ...
        'assocUseBodyRoadGate', false);
    moduleSet = sprintf('combo + yaw=%g(%d) pitch=%g(%d)', ...
        yawThresh, useYaw, pitchThresh, usePitch);
    v = variant(name, "motion_sweep", description, moduleSet, params);
end

function params = pfMinimalParams()
    params = struct( ...
        'initUse', false, ...
        'pfInitXStd', 0.0, ...
        'pfInitYStd', 0.0, ...
        'pfInitYawStdDeg', 0.0, ...
        'pfUseMeasurementUpdate', false, ...
        'pfProcessForwardStd', 0.0, ...
        'pfProcessLateralStd', 0.0, ...
        'pfProcessYawStdDeg', 0.0, ...
        'pfProcessTransScale', 0.0, ...
        'pfProcessYawScale', 0.0, ...
        'pfRoughenAfterResample', false, ...
        'pfWeightUniformMix', 0.0);
end

function params = pfStabilizationParams()
    params = struct( ...
        'pfProcessForwardStd', 0.015, ...
        'pfProcessLateralStd', 0.04, ...
        'pfProcessYawStdDeg', 0.10, ...
        'pfProcessTransScale', 0.015, ...
        'pfProcessYawScale', 0.03, ...
        'pfProcessNoiseFrame', 'body', ...
        'pfRoughenAfterResample', true, ...
        'pfRoughenXStd', 0.01, ...
        'pfRoughenYStd', 0.02, ...
        'pfRoughenYawStdDeg', 0.03);
end

function params = measurementMinimalParams()
    params = struct( ...
        'pfUseMeasurementUpdate', true, ...
        'assocUseYawingRejection', false, ...
        'assocUsePitchingRejection', false, ...
        'assocUseMinCurveChordRule', false, ...
        'assocUseMinBodyDistanceRule', false, ...
        'assocRequireStartConnection', false, ...
        'assocUseBodyRoadGate', false, ...
        'assocUseCameraFovGate', false, ...
        'assocUseCurveMapCorrespondenceRule', false, ...
        'likelihoodUseRobust', false, ...
        'pfLikelihoodTemperature', 1.0, ...
        'pfLikelihoodMaxLogSpan', inf, ...
        'pfWeightUniformMix', 0.0, ...
        'pfMinAssociatedParticleRatio', 0.0);
end

function params = robustLikelihoodParams()
    params = struct( ...
        'likelihoodUseRobust', true, ...
        'likelihoodSigma', 1.75, ...
        'likelihoodRobustScale', 1.0, ...
        'likelihoodMaxEffectiveSamples', 12, ...
        'likelihoodCurveMissLogPenalty', -24.0, ...
        'likelihoodMaxCurvePenalty', 20.0, ...
        'likelihoodInlierReward', 0.75, ...
        'likelihoodMissLogPenalty', -90.0);
end

function params = likelihoodStabilizationParams()
    params = struct( ...
        'pfLikelihoodTemperature', 6.0, ...
        'pfLikelihoodMaxLogSpan', 22.0, ...
        'pfWeightUniformMix', 0.02, ...
        'pfMinAssociatedParticleRatio', 0.02);
end

function params = queryRuleParams()
    params = struct( ...
        'assocUseYawingRejection', true, ...
        'assocUsePitchingRejection', true, ...
        'assocUseMinCurveChordRule', true, ...
        'assocUseMinBodyDistanceRule', true, ...
        'assocRequireStartConnection', false, ...
        'assocAllowSingleCurveWithoutConnection', true);
end

function params = initAlignmentParams()
    params = struct( ...
        'initUse', true, ...
        'initUseTrajectoryAlignment', true, ...
        'initUseLongitudinalCorrection', true, ...
        'pfInitXStd', 3.0, ...
        'pfInitYStd', 1.5, ...
        'pfInitYawStdDeg', 2.0);
end

function v = variant(name, stage, description, moduleSet, params)
    v = struct('name', string(name), 'stage', string(stage), ...
        'description', string(description), 'moduleSet', string(moduleSet), ...
        'params', params);
end

function data = loadExperimentData(cfg)
    estRawData = readtable(cfg.estDir, 'VariableNamingRule', 'preserve');
    queryTimestamp = estRawData{:, 1}.';

    estPos = [estRawData{:, 2}, estRawData{:, 3}].';
    estPos0 = estPos(:, 1);
    estQuat0 = [estRawData{1, 8}, estRawData{1, 5}, estRawData{1, 6}, estRawData{1, 7}].';
    estYaw0 = Quat2RPY(estQuat0);
    estYaw0 = estYaw0(3);
    r0 = [cos(estYaw0), -sin(estYaw0); sin(estYaw0), cos(estYaw0)];
    vioXY = r0.' * (estPos - estPos0);

    estQuat = [estRawData{:, 8}, estRawData{:, 5}, estRawData{:, 6}, estRawData{:, 7}].';
    estRpy = zeros(3, size(estQuat, 2));
    for k = 1:size(estQuat, 2)
        estRpy(:, k) = Quat2RPY(estQuat(:, k));
    end

    estRelRawData = readtable(cfg.estRelDir);
    len = height(estRelRawData) + 1;
    dYaw = atan2(sin(estRelRawData.dyaw), cos(estRelRawData.dyaw)).';
    dSE2 = [estRelRawData.dtx_body.'; estRelRawData.dty_body.'; dYaw];

    [~, gtPoses] = genRef(cfg, queryTimestamp);
    gtPoseMapGlobal = pose12ToSE3(gtPoses);
    gtPoseMapLocal = transformToInitLocal(gtPoseMapGlobal, "Yaw");
    gtXY = reshape(gtPoseMapLocal(1:2, 4, :), 2, []);

    queryBezier = loadBezier(cfg, queryTimestamp);
    queryBezier = annotateQueryMotion(cfg, queryBezier, estRpy, queryTimestamp);

    [mapDB, ~] = buildMap(cfg, gtPoseMapGlobal(:, :, 1));
    xTrue0InMap = initialAlignmentTruth(cfg, gtPoseMapGlobal(:, :, 1), gtPoseMapGlobal(:, :, 1));

    data = struct();
    data.len = len;
    data.dSE2 = dSE2;
    data.queryBezier = queryBezier;
    data.mapDB = mapDB;
    data.gtXY = gtXY;
    data.vioXY = vioXY;
    data.gtPoseMapGlobal = gtPoseMapGlobal;
    data.xTrue0InMap = xTrue0InMap;
end

function [x0, x0Align, alignInfo, elapsedSec] = computeInitialState(cfg, data)
    elapsed = tic;
    if getLogical(cfg, 'initUse', true)
        if getLogical(cfg, 'initUseTrajectoryAlignment', true)
            [x0Align, alignInfo] = estimateInitialTrajectoryAlignment(cfg, data.mapDB, data.queryBezier, data.dSE2, data.len);
        else
            [x0Align, alignInfo] = estimateInitialAlignment(cfg, data.mapDB, data.queryBezier);
        end
    else
        x0Align = [0; 0; 0];
        alignInfo = struct('frameIdx', [], 'selectedFrameIdx', [], 'logLikelihood', NaN);
    end
    elapsedSec = toc(elapsed);
    x0 = selectPfInitialState(cfg, x0Align);
end

function p0 = initialCovariance(cfg)
    p0 = diag([ ...
        getScalar(cfg, 'pfInitXStd', 0.0)^2, ...
        getScalar(cfg, 'pfInitYStd', 0.0)^2, ...
        deg2rad(getScalar(cfg, 'pfInitYawStdDeg', 0.0))^2]);
end

function stats = countBezierDatasetStats(cfg, meas)
    stats = struct('usableFrames', 0, 'usableCurves', 0, ...
        'rejectYawing', 0, 'rejectPitching', 0, 'rejectShortChord', 0, ...
        'rejectNearBody', 0, 'rejectIsolatedStart', 0);
    for k = 1:numel(meas)
        frame = buildQueryBezierFrame(cfg, meas(k));
        if frame.hasUsableCurves
            stats.usableFrames = stats.usableFrames + 1;
            stats.usableCurves = stats.usableCurves + numel(frame.usableIdx);
        end
        if isfield(frame, 'rejectSummary')
            stats.rejectYawing = stats.rejectYawing + getRejectCount(frame.rejectSummary, 'yawing');
            stats.rejectPitching = stats.rejectPitching + getRejectCount(frame.rejectSummary, 'pitching');
            stats.rejectShortChord = stats.rejectShortChord + getRejectCount(frame.rejectSummary, 'shortChord');
            stats.rejectNearBody = stats.rejectNearBody + getRejectCount(frame.rejectSummary, 'nearBody');
            stats.rejectIsolatedStart = stats.rejectIsolatedStart + getRejectCount(frame.rejectSummary, 'isolatedStart');
        end
    end
end

function summary = summarizePfDiag(pfDiag, nEff, nParticles)
    summary = struct();
    summary.usedUpdateFrames = sum(pfDiag.usedUpdate);
    summary.resampleCount = sum(pfDiag.resampled);
    summary.meanNeffRatio = mean(nEff, 'omitnan') / max(nParticles, 1);
    summary.stdNeffRatio = std(nEff ./ max(nParticles, 1), 0, 'omitnan');
    summary.meanAssociatedParticleRatio = mean(pfDiag.associatedParticleRatio, 'omitnan');
    summary.meanRoadGatePassRatio = mean(pfDiag.roadGatePassRatio, 'omitnan');
    summary.meanMatchedCurveCount = mean(pfDiag.matchedCurveCountMean, 'omitnan');
    summary.meanResidual = mean(pfDiag.meanResidual, 'omitnan');
end

function summaryTable = summarizeResults(rawResults)
    keys = unique(rawResults(:, {'variantName', 'nParticles'}), 'rows', 'stable');
    rows = repmat(emptySummaryRow(), 0, 1);
    for i = 1:height(keys)
        mask = rawResults.variantName == keys.variantName(i) & ...
            rawResults.nParticles == keys.nParticles(i);
        subset = rawResults(mask, :);
        row = emptySummaryRow();
        row.variantName = keys.variantName(i);
        row.stage = subset.stage(1);
        row.description = subset.description(1);
        row.moduleSet = subset.moduleSet(1);
        row.nRuns = height(subset);
        row.nParticles = subset.nParticles(1);
        row.meanVioRmse = mean(subset.vioRmse, 'omitnan');
        row.meanPfRmse = mean(subset.pfRmse, 'omitnan');
        row.stdPfRmse = std(subset.pfRmse, 0, 'omitnan');
        row.meanImprovement = mean(subset.improvement, 'omitnan');
        row.meanImprovementPct = mean(subset.improvementPct, 'omitnan');
        row.stdImprovementPct = std(subset.improvementPct, 0, 'omitnan');
        row.worstImprovementPct = min(subset.improvementPct);
        row.bestImprovementPct = max(subset.improvementPct);
        row.beatsVioRate = mean(double(subset.beatsVio), 'omitnan');
        row.meanNeffRatio = mean(subset.meanNeffRatio, 'omitnan');
        row.meanAssociatedParticleRatio = mean(subset.meanAssociatedParticleRatio, 'omitnan');
        row.meanRoadGatePassRatio = mean(subset.meanRoadGatePassRatio, 'omitnan');
        row.meanResidual = mean(subset.meanResidual, 'omitnan');
        row.meanElapsedSec = mean(subset.elapsedSec, 'omitnan');
        rows(end + 1) = row; %#ok<AGROW>
    end
    summaryTable = struct2table(rows);
    if height(unique(summaryTable(:, 'variantName'), 'rows')) == 1
        summaryTable = sortrows(summaryTable, 'nParticles');
    else
        summaryTable = sortrows(summaryTable, 'meanPfRmse');
    end
end

function cfg = applyParams(cfg, params)
    names = fieldnames(params);
    for i = 1:numel(names)
        cfg.(names{i}) = params.(names{i});
    end
end

function cfg = applyMapInitSeed(cfg, seed)
    cfg.mapInitErrorSeed = seed;
    if isempty(seed) || isnan(seed)
        return;
    end
    stream = RandStream('mt19937ar', 'Seed', seed);
    cfg.mapInitXError = 3 * randn(stream, 1);
    cfg.mapInitYError = 3 * randn(stream, 1);
    cfg.mapInitYawError = deg2rad(10) * randn(stream, 1);
end

function row = emptyResultRow()
    row = struct( ...
        'mode', "", ...
        'variantName', "", ...
        'stage', "", ...
        'description', "", ...
        'moduleSet', "", ...
        'nParticles', NaN, ...
        'pfSeed', NaN, ...
        'mapSeed', NaN, ...
        'nSamples', NaN, ...
        'vioRmse', NaN, ...
        'pfRmse', NaN, ...
        'improvement', NaN, ...
        'improvementPct', NaN, ...
        'beatsVio', false, ...
        'vioMeanError', NaN, ...
        'pfMeanError', NaN, ...
        'vioFinalError', NaN, ...
        'pfFinalError', NaN, ...
        'pfAxisRmseX', NaN, ...
        'pfAxisRmseY', NaN, ...
        'alignElapsedSec', NaN, ...
        'alignX', NaN, ...
        'alignY', NaN, ...
        'alignYawDeg', NaN, ...
        'alignLogLikelihood', NaN, ...
        'alignSelectedFrames', NaN, ...
        'usableFrames', NaN, ...
        'usableCurves', NaN, ...
        'rejectYawing', NaN, ...
        'rejectPitching', NaN, ...
        'rejectShortChord', NaN, ...
        'rejectNearBody', NaN, ...
        'rejectIsolatedStart', NaN, ...
        'usedUpdateFrames', NaN, ...
        'resampleCount', NaN, ...
        'meanNeffRatio', NaN, ...
        'stdNeffRatio', NaN, ...
        'meanAssociatedParticleRatio', NaN, ...
        'meanRoadGatePassRatio', NaN, ...
        'meanMatchedCurveCount', NaN, ...
        'meanResidual', NaN, ...
        'elapsedSec', NaN);
end

function row = emptySummaryRow()
    row = struct( ...
        'variantName', "", ...
        'stage', "", ...
        'description', "", ...
        'moduleSet', "", ...
        'nRuns', NaN, ...
        'nParticles', NaN, ...
        'meanVioRmse', NaN, ...
        'meanPfRmse', NaN, ...
        'stdPfRmse', NaN, ...
        'meanImprovement', NaN, ...
        'meanImprovementPct', NaN, ...
        'stdImprovementPct', NaN, ...
        'worstImprovementPct', NaN, ...
        'bestImprovementPct', NaN, ...
        'beatsVioRate', NaN, ...
        'meanNeffRatio', NaN, ...
        'meanAssociatedParticleRatio', NaN, ...
        'meanRoadGatePassRatio', NaN, ...
        'meanResidual', NaN, ...
        'meanElapsedSec', NaN);
end

function n = selectedFrameCount(alignInfo)
    n = NaN;
    if isstruct(alignInfo) && isfield(alignInfo, 'selectedFrameIdx') && ~isempty(alignInfo.selectedFrameIdx)
        n = numel(alignInfo.selectedFrameIdx);
    elseif isstruct(alignInfo) && isfield(alignInfo, 'frameIdx') && ~isempty(alignInfo.frameIdx)
        n = numel(alignInfo.frameIdx);
    end
end
