function results = runPfTuning(nParticles)
%RUNPFTUNING Hyper-parameter sweep for inference Bezier measurements.

    if nargin < 1 || isempty(nParticles)
        nParticles = [];
    end

    addpath estimator\ map\ math\ rosservice\

    baseCfg = loadConfig();
    baseCfg.yamlLogProgress = false;
    baseCfg.pfLogProgress = false;
    baseCfg.pfVisualizeMapMatching = false;
    if ~isempty(nParticles)
        baseCfg.pfNumParticles = nParticles;
    end

    data = loadTuningData(baseCfg);
    variants = makeTuningVariants();

    nVariant = numel(variants);
    name = strings(nVariant, 1);
    usableFrames = zeros(nVariant, 1);
    usableCurves = zeros(nVariant, 1);
    vioRmse = zeros(nVariant, 1);
    pfRmse = zeros(nVariant, 1);
    improvementPct = zeros(nVariant, 1);
    meanNeffRatio = zeros(nVariant, 1);
    elapsedSec = zeros(nVariant, 1);

    for i = 1:nVariant
        cfg = applyTuningVariant(baseCfg, variants(i));
        stats = countUsableBezierFrames(cfg, data.queryBezier);

        fprintf('\n[%d/%d] %s: %s\n', i, nVariant, variants(i).name, variants(i).note);
        fprintf('  usable before PF: %d frames / %d curves\n', stats.usableFrames, stats.usableCurves);

        tic;
        [xhat, nEff] = sir(cfg, data.mapDB, [0; 0; 0], zeros(3), ...
            data.dSE2, data.queryBezier, [], data.len, cfg.pfNumParticles);
        elapsedSec(i) = toc;

        metrics = evaluateTrajectories(data.gtXY, data.vioXY, xhat(1:2, :));

        name(i) = variants(i).name;
        usableFrames(i) = stats.usableFrames;
        usableCurves(i) = stats.usableCurves;
        vioRmse(i) = metrics.vio.rmse;
        pfRmse(i) = metrics.pf.rmse;
        improvementPct(i) = metrics.rmseImprovementPct;
        meanNeffRatio(i) = mean(nEff, 'omitnan') / cfg.pfNumParticles;

        fprintf('  PF RMSE=%.3f m, VIO RMSE=%.3f m, improvement=%.2f%%, mean N_eff=%.2f, %.1f sec\n', ...
            pfRmse(i), vioRmse(i), improvementPct(i), meanNeffRatio(i), elapsedSec(i));
    end

    results = table(name, usableFrames, usableCurves, vioRmse, pfRmse, ...
        improvementPct, meanNeffRatio, elapsedSec);
    results = sortrows(results, 'pfRmse');

    outPath = fullfile(fileparts(mfilename('fullpath')), 'pf_tuning_results.csv');
    writetable(results, outPath);
    fprintf('\nSaved tuning table: %s\n', outPath);
    disp(results);
end

function data = loadTuningData(cfg)
    estRawData = readtable(cfg.estDir, 'VariableNamingRule', 'preserve');
    queryTimestamp = estRawData{:, 1}.';

    estPos = [estRawData{:, 2}, estRawData{:, 3}].';
    estPos0 = estPos(:, 1);
    estQuat0 = [estRawData{1, 8}, estRawData{1, 5}, estRawData{1, 6}, estRawData{1, 7}].';
    estYaw0 = Quat2RPY(estQuat0);
    estYaw0 = estYaw0(3);
    r0 = [cos(estYaw0), -sin(estYaw0); sin(estYaw0), cos(estYaw0)];
    vioXY = r0.' * (estPos - estPos0);

    estQuat = [estRawData{:, 8}, estRawData{:, 5}, estRawData{:, 6}, estRawData{:, 7}].';
    estRpy = zeros(3, size(estQuat, 2));
    for k = 1:size(estQuat, 2)
        estRpy(:, k) = Quat2RPY(estQuat(:, k));
    end

    estRelRawData = readtable(cfg.estRelDir);
    len = height(estRelRawData) + 1;
    dYaw = atan2(sin(estRelRawData.dyaw), cos(estRelRawData.dyaw)).';
    dSE2 = [estRelRawData.dtx_body.'; estRelRawData.dty_body.'; dYaw];

    [~, gtPoses] = genRef(cfg, queryTimestamp);
    gtPoseMapGlobal = pose12ToSE3(gtPoses);
    gtPoseMapLocal = transformToInitLocal(gtPoseMapGlobal, "Yaw");
    gtXY = reshape(gtPoseMapLocal(1:2, 4, :), 2, []);

    queryBezier = loadBezier(cfg, queryTimestamp);
    queryBezier = annotateQueryMotion(cfg, queryBezier, estRpy, queryTimestamp);

    [mapDB, ~] = buildMap(cfg, gtPoseMapGlobal(:, :, 1));

    data = struct();
    data.len = len;
    data.dSE2 = dSE2;
    data.queryBezier = queryBezier;
    data.mapDB = mapDB;
    data.gtXY = gtXY;
    data.vioXY = vioXY;
end

function variants = makeTuningVariants()
    variants = struct('name', {}, 'note', {}, 'params', {});

    variants(end + 1) = variant("baseline", ...
        "current GT-tuned parameters on inference data", struct());

    variants(end + 1) = variant("strict_connected", ...
        "require connected starts; reject isolated inference fragments", struct( ...
            'assocRequireStartConnection', true, ...
            'assocAllowSingleCurveWithoutConnection', false, ...
            'assocConnectionTol', 3.0));

    variants(end + 1) = variant("long_curves", ...
        "prefer longer curves and slightly farther body distance", struct( ...
            'assocMinCurveChord', 8.0, ...
            'assocMinBodyDistance', 3.0));

    variants(end + 1) = variant("strict_long", ...
        "connected + long curve filtering", struct( ...
            'assocRequireStartConnection', true, ...
            'assocAllowSingleCurveWithoutConnection', false, ...
            'assocConnectionTol', 3.0, ...
            'assocMinCurveChord', 8.0, ...
            'assocMinBodyDistance', 3.0));

    variants(end + 1) = variant("wide_assoc", ...
        "noisier inference geometry: wider association and sigma", struct( ...
            'assocMaxCurveMapDist', 7.0, ...
            'likelihoodSigma', 2.0, ...
            'likelihoodMaxCurvePenalty', 18.0, ...
            'likelihoodCurveMissLogPenalty', -22.0));

    variants(end + 1) = variant("strict_wide", ...
        "connected filtering with wider residual model", struct( ...
            'assocRequireStartConnection', true, ...
            'assocAllowSingleCurveWithoutConnection', false, ...
            'assocConnectionTol', 3.0, ...
            'assocMaxCurveMapDist', 7.0, ...
            'likelihoodSigma', 2.0, ...
            'likelihoodMaxCurvePenalty', 18.0, ...
            'likelihoodCurveMissLogPenalty', -22.0));

    variants(end + 1) = variant("low_info", ...
        "down-weight noisy inference frames", struct( ...
            'pfLikelihoodTemperature', 7.0, ...
            'pfLikelihoodMaxLogSpan', 18.0, ...
            'likelihoodMaxEffectiveSamples', 10, ...
            'likelihoodInlierReward', 0.5));

    variants(end + 1) = variant("strict_low_info", ...
        "connected filtering + down-weighted likelihood", struct( ...
            'assocRequireStartConnection', true, ...
            'assocAllowSingleCurveWithoutConnection', false, ...
            'assocConnectionTol', 3.0, ...
            'pfLikelihoodTemperature', 7.0, ...
            'pfLikelihoodMaxLogSpan', 18.0, ...
            'likelihoodMaxEffectiveSamples', 10, ...
            'likelihoodInlierReward', 0.5));

    variants(end + 1) = variant("road_gate_loose", ...
        "loosen road gate for map/inference disagreement", struct( ...
            'assocRoadWidthScale', 2.0, ...
            'assocMaxCurveMapDist', 7.0, ...
            'likelihoodSigma', 2.0));

    variants(end + 1) = variant("smooth_pf", ...
        "lower PF process diffusion for inference measurement noise", struct( ...
            'pfProcessForwardStd', 0.015, ...
            'pfProcessLateralStd', 0.04, ...
            'pfProcessYawStdDeg', 0.10, ...
            'pfProcessTransScale', 0.015, ...
            'pfProcessYawScale', 0.03, ...
            'pfRoughenXStd', 0.01, ...
            'pfRoughenYStd', 0.02, ...
            'pfRoughenYawStdDeg', 0.03));

    variants(end + 1) = variant("strict_smooth", ...
        "connected filtering + smoother PF", struct( ...
            'assocRequireStartConnection', true, ...
            'assocAllowSingleCurveWithoutConnection', false, ...
            'assocConnectionTol', 3.0, ...
            'pfProcessForwardStd', 0.015, ...
            'pfProcessLateralStd', 0.04, ...
            'pfProcessYawStdDeg', 0.10, ...
            'pfProcessTransScale', 0.015, ...
            'pfProcessYawScale', 0.03, ...
            'pfRoughenXStd', 0.01, ...
            'pfRoughenYStd', 0.02, ...
            'pfRoughenYawStdDeg', 0.03));
end

function v = variant(name, note, params)
    v = struct('name', string(name), 'note', string(note), 'params', params);
end

function cfg = applyTuningVariant(cfg, variant)
    names = fieldnames(variant.params);
    for i = 1:numel(names)
        cfg.(names{i}) = variant.params.(names{i});
    end
end

function stats = countUsableBezierFrames(cfg, meas)
    usableFrames = 0;
    usableCurves = 0;
    for k = 1:numel(meas)
        frame = buildQueryBezierFrame(cfg, meas(k));
        if frame.hasUsableCurves
            usableFrames = usableFrames + 1;
            usableCurves = usableCurves + numel(frame.usableIdx);
        end
    end

    stats = struct('usableFrames', usableFrames, 'usableCurves', usableCurves);
end
